#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

filter=""
dry="0"

cd $script_dir
scripts=(find runs -maxdepth 1 -mindepth 1 -executable -type f)

while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    shift
done

for script in "${scripts[@]}"; do
    if echo "$script" | grep -qv "$filter"; then
        echo "filtered: $filter -- $script"
        continue
    fi
    ./$script
done